version: "3.3"

services:
  app:
    container_name: web-app
    network_mode: "host"
    build: 
      context: ./
    ports:
      - 8080:8080
    environment:
      - DB_HOST=localhost
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=simpleapi
